# Generated by Django 5.0.6 on 2024-07-04 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="estoque",
            fields=[
                (
                    "timestampedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.timestampedmodel",
                    ),
                ),
                (
                    "nf",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Nota Fiscal"
                    ),
                ),
                (
                    "movimentos",
                    models.CharField(
                        choices=[("e", "entrada"), ("s", "saída")], max_length=1
                    ),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
            bases=("core.timestampedmodel",),
        ),
    ]
