# Generated by Django 5.0.6 on 2024-07-04 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0001_initial"),
        ("produto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstoqueItens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                ("saldo", models.PositiveIntegerField()),
                (
                    "estoque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estoque.estoque",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produto.produtos",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
    ]
