# Generated by Django 5.1.15 on 2026-05-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    "CREATE INDEX CONCURRENTLY IF NOT EXISTS django_session_expire_date_idx "
                    "ON django_session (expire_date)"
                ),
            ],
            reverse_sql=[
                ("DROP INDEX IF EXISTS django_session_expire_date_idx"),
            ],
        ),
    ]
