services:
  db:
    image: "postgres:16.8-alpine3.21"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 3

  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile.dev
    volumes:
      - ../:/app
      - ../staticfiles/:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ../.env.development
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py collectstatic --noinput --clear
            python manage.py makemigrations || exit 1;
            python manage.py migrate || exit 1;
            exec python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
  static_volume: