# Generated by Django 5.0.6 on 2024-07-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ncm", models.CharField(max_length=8, verbose_name="NCM")),
                ("produto", models.CharField(max_length=100, unique=True)),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="preço"
                    ),
                ),
                ("estoque", models.IntegerField(verbose_name="estoque atual")),
                (
                    "estoque_minimo",
                    models.PositiveIntegerField(
                        default=0, verbose_name="estoque mínimo"
                    ),
                ),
                ("nivel_estoque", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("produto",),
            },
        ),
    ]
