# Generated by Django 5.0.6 on 2024-07-04 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Produtos",
            new_name="Produto",
        ),
    ]
