# Generated by Django 5.1.15 on 2026-04-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produto",
            options={"ordering": ("produto",)},
        ),
        migrations.AddIndex(
            model_name="produto",
            index=models.Index(fields=["produto"], name="idx_produto_nome"),
        ),
        migrations.AddIndex(
            model_name="produto",
            index=models.Index(fields=["codigoBarra"], name="idx_produto_codbar"),
        ),
        migrations.AddIndex(
            model_name="produto",
            index=models.Index(
                fields=["estoque", "estoque_minimo"], name="idx_produto_estoque"
            ),
        ),
    ]
