# Generated by Django 5.0.6 on 2024-07-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0002_rename_produtos_produto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="nivel_estoque",
            field=models.BooleanField(default=False, verbose_name="Está em falta?"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="produto",
            field=models.TextField(max_length=100, unique=True, verbose_name="produto"),
        ),
    ]
