# Generated by Django 5.0.6 on 2024-07-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0005_alter_produto_nivel_estoque"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produto",
            options={"ordering": ("-produto",)},
        ),
        migrations.RemoveField(
            model_name="produto",
            name="preco",
        ),
        migrations.AddField(
            model_name="produto",
            name="preco_custo",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=7,
                verbose_name="preço de custo",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="preco_venda",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=7,
                verbose_name="preço de venda",
            ),
        ),
    ]
