# Generated by Django 5.0.6 on 2024-07-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0006_alter_produto_options_remove_produto_preco_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="margem_vendas",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=6,
                verbose_name="margem de vendas",
            ),
            preserve_default=False,
        ),
    ]
