# Generated by Django 5.0.6 on 2024-07-25 23:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0007_produto_margem_vendas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="estoque",
            field=models.IntegerField(verbose_name="Estoque Atual"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="estoque_minimo",
            field=models.PositiveIntegerField(default=0, verbose_name="Estoque Mínimo"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="margem_vendas",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Margem de Vendas",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nivel_estoque",
            field=models.BooleanField(default=False, verbose_name="Nível do Estoque"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco_custo",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=7,
                verbose_name="Preço de Custo",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco_venda",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=7,
                verbose_name="Preço de Venda",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="produto",
            field=models.TextField(max_length=100, unique=True, verbose_name="Produto"),
        ),
    ]
