# Generated by Django 5.0.6 on 2024-08-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0008_alter_produto_estoque_alter_produto_estoque_minimo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="codigoBarra",
            field=models.CharField(max_length=16, verbose_name="Codigo de  de Barra"),
        ),
    ]
