# Generated by Django 5.0.6 on 2024-08-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0009_alter_produto_codigobarra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="codigoBarra",
            field=models.CharField(max_length=16, verbose_name="Codigo de Barra"),
        ),
    ]
