# Generated by Django 5.0.6 on 2024-08-10 00:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0011_categoria_alter_produto_options_produto_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "preco_venda",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=7,
                        verbose_name="Preço de Venda",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "metodo_pagamento",
                    models.CharField(
                        choices=[
                            ("PIX", "PIX"),
                            ("credito", "Crédito"),
                            ("debito", "Débito"),
                            ("dinheiro", "Dinheiro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_venda", models.DateTimeField(auto_now_add=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produto.produto",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
        name='Venda',
    ),
    ]
