# Generated by Django 5.0.6 on 2024-09-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0014_tab_tabitem_tab_produtos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="codigoBarra",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="Codigo de Barra"
            ),
        ),
    ]
