# Generated by Django 5.0.6 on 2024-10-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0020_alter_tabitem_data_criacao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemcompra",
            name="compra",
        ),
        migrations.RemoveField(
            model_name="itemcompra",
            name="produto",
        ),
        migrations.RemoveField(
            model_name="tab",
            name="produtos",
        ),
        migrations.RemoveField(
            model_name="tabitem",
            name="tab",
        ),
        migrations.RemoveField(
            model_name="tabitem",
            name="adicionado_por",
        ),
        migrations.RemoveField(
            model_name="tabitem",
            name="produto",
        ),
        migrations.DeleteModel(
            name="Compra",
        ),
        migrations.DeleteModel(
            name="ItemCompra",
        ),
        migrations.DeleteModel(
            name="Tab",
        ),
        migrations.DeleteModel(
            name="TabItem",
        ),
    ]
