# Generated by Django 5.0.6 on 2025-07-23 01:17

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SessaoCaixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_abertura",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "valor_fechamento_calculado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total que o sistema calculou no fechamento",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "valor_fechamento_informado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total que o usuário contou no caixa",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "diferenca",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("data_abertura", models.DateTimeField(auto_now_add=True)),
                ("data_fechamento", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ABERTO", "Aberto"), ("FECHADO", "Fechado")],
                        default="ABERTO",
                        max_length=10,
                    ),
                ),
                (
                    "usuario_abertura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessoes_abertas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_fechamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessoes_fechadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovimentacaoCaixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ABERTURA", "Abertura de Caixa"),
                            ("SUPRIMENTO", "Suprimento (Entrada)"),
                            ("VENDA", "Venda em Dinheiro"),
                            ("SANGRIA", "Sangria (Retirada)"),
                        ],
                        max_length=15,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descricao", models.CharField(blank=True, max_length=200)),
                (
                    "data_movimentacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sessao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes",
                        to="caixa.sessaocaixa",
                    ),
                ),
            ],
        ),
    ]
