# Generated by Django 5.0.6 on 2024-11-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comandas", "0003_alter_comment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.CharField(max_length=48, unique=True, verbose_name="Content"),
        ),
    ]
