# Generated by Django 5.0.6 on 2025-07-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comandas", "0004_alter_comment_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="tab",
            name="data_fechamento",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data de Fechamento"
            ),
        ),
        migrations.AddField(
            model_name="tab",
            name="status",
            field=models.CharField(
                choices=[
                    ("ATIVA", "Ativa"),
                    ("VAZIA", "Vazia"),
                    ("FECHADA", "Fechada"),
                ],
                db_index=True,
                default="VAZIA",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
