# Generated by Django 5.0.6 on 2025-07-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comandas", "0005_tab_data_fechamento_tab_status"),
    ]

    operations = [
            migrations.RunSQL(
                "ALTER TABLE comandas_tab DROP COLUMN IF EXISTS telefone_cliente;",
            )
        ]
